name: Build LaTeX document
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        args: -jobname=compiled -pdf -interaction=nonstopmode
        compiler: latexmk
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: compiled.pdf
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        
